services:
  api:
    build:
      target: development
    volumes:
      - ./src:/app/src
    expose:
      - "4000"
    ports:
      - "4000:4000"
    depends_on:
      - db
      - redis

  nginx:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/default.local.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/nginx/entrypoint.local.sh:/docker-entrypoint.d/99-entrypoint.local.sh:ro
      - nginx_certs:/etc/nginx/certs

  db:
    image: postgres:15-alpine
    container_name: cineflix-main-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_POSTGRESQL_MAIN_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_POSTGRESQL_MAIN_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_POSTGRESQL_MAIN_DATABASE:-cineflix}
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - cineflix-network

  redis:
    image: redis:alpine
    container_name: cineflix-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - cineflix-network

volumes:
  pgdata:
  nginx_certs:
