services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: cineflix-api
        restart: always
        env_file:
            - .env
        networks:
            - cineflix-network
        environment:
            - NPM_CONFIG_UPDATE_NOTIFIER=false

    nginx:
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        container_name: cineflix-nginx
        restart: always
        depends_on:
            - api
        networks:
            - cineflix-network

networks:
    cineflix-network:
        driver: bridge
